source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '~> 4.0.0'
gem 'pg', '~> 0.16.0'
gem 'unicorn', '~> 4.6.3'
gem 'jquery-rails', '~> 3.0.4'
gem 'jquery-ui-rails', '~> 4.0.4'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise', '~> 3.0.2'
gem 'devise-async', '~> 0.7.0'
gem 'devise_invitable', git: 'git://github.com/scambra/devise_invitable.git'
gem 'fullcalendar-rails', '~> 1.6.1.0'

gem 'turbolinks', '~> 1.3.0'

gem 'jquery-turbolinks', '~> 1.0.0'
gem 'bloggy', '~> 0.2.2'
gem 'stripe', '~> 1.8.4'
gem 'newrelic_rpm', '~> 3.6.6.147'
gem 'sidekiq', '~> 2.13.1'
gem 'sinatra', '~> 1.4.2', require: false
gem 'slim', '~> 2.0.0'
gem 'hirefire-resource', git: 'git://github.com/meskyanichi/hirefire-resource.git', branch: 'schedule_and_retry_fix'
gem 'memcachier', '~> 0.0.2'
gem 'dalli', '~> 2.6.4'
gem 'will_paginate', '~> 3.0.4'
gem 'best_in_place', git: 'git://github.com/bernat/best_in_place.git'

gem 'sass-rails',   '~> 4.0.0'
gem 'uglifier', '>= 2.1.2'
gem 'bootstrap-sass', '2.3.2.1'
gem 'd3_rails', '~> 3.2.8'
gem 'asset_sync', '~> 0.5.4'
gem 'heroku-api', '~> 0.3.14'
gem 'rack-cache', '~> 1.2'
gem 'font-awesome-rails', '~> 3.2.1.3'
gem 'rack-timeout', '~> 0.0.4'
gem 'filepicker-rails', '0.1.0'

group :development, :test do
  gem 'rspec-rails', '~> 2.14.0'
  gem 'shoulda-matchers', git: 'git://github.com/thoughtbot/shoulda-matchers.git' , branch: 'dp-rails-four'
  gem 'fixture_builder', '~> 0.3'
  gem 'capybara', '~> 2.1'
  gem 'quiet_assets', '~> 1.0'
  gem 'gemnasium', '~> 2.0'
end
