source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '~> 4.0.0.rc2'
gem 'pg', '~> 0.15.1'
gem 'unicorn', '~> 4.6.0'
gem 'jquery-rails', '~> 2.2.2'
gem 'jquery-ui-rails', '~> 4.0.3'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise', '~> 3.0.0.rc'
gem 'fullcalendar-rails', '~> 1.6.1.0'

gem 'turbolinks', '~> 1.2.0'

gem 'jquery-turbolinks', '~> 1.0.0'
gem 'bloggy', '~> 0.2.1'
gem 'jekyll', '~> 0.12.0'
gem 'stripe', '~> 1.8.3'
gem 'newrelic_rpm', '~> 3.6.3.111'
gem 'sidekiq', '~> 2.12.4'
gem 'sinatra', '~> 1.4.2', require: false
gem 'slim', '~> 2.0.0'
gem 'hirefire-resource', '~> 0.1.1'
gem 'memcachier', '~> 0.0.2'
gem 'dalli', '~> 2.6.4'
gem 'will_paginate', '~> 3.0.4'
gem 'intercom-rails', '~> 0.2.21'
gem 'best_in_place', git: 'git://github.com/bernat/best_in_place.git'

gem 'sass-rails',   '~> 4.0.0.rc1'
gem 'uglifier', '>= 2.1.1'
gem 'bootstrap-sass', '2.3.2.0'
gem 'd3_rails', '~> 3.1.10'
gem 'asset_sync', '~> 0.5.4'
gem 'heroku-api', '~> 0.3.12'
gem 'rack-cache', '~> 1.2'
gem 'devise-async', '~> 0.7.0'

group :development, :test do
  gem 'rspec-rails', '~> 2.14.0.rc1'
  gem 'shoulda-matchers', git: 'git://github.com/thoughtbot/shoulda-matchers.git' , branch: 'dp-rails-four'
  gem 'fixture_builder', git: 'git://github.com/rdy/fixture_builder.git'
  gem 'capybara', '~> 2.1'
  gem 'quiet_assets', '~> 1.0'
  gem 'gemnasium', '~> 2.0'
end
